"""Initial schema

Revision ID: 7ae5a44559b1
Revises: 
Create Date: 2026-06-21 22:39:09.807364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ae5a44559b1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('asset_type', sa.String(length=20), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_ticker'), 'assets', ['ticker'], unique=True)
    op.create_table('brokers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('commission_type', sa.String(length=20), nullable=False),
    sa.Column('commission_fixed_eur', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('commission_pct', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('min_commission_eur', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('max_commission_eur', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('custody_fee_annual_pct', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('fx_spread_pct', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investor_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_type', sa.String(length=20), nullable=False),
    sa.Column('risk_tolerance_score', sa.Integer(), nullable=False),
    sa.Column('time_horizon_years', sa.Integer(), nullable=False),
    sa.Column('investment_objective', sa.String(length=100), nullable=False),
    sa.Column('monthly_contribution', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('max_acceptable_drawdown_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('questionnaire_answers', sa.Text(), nullable=True),
    sa.Column('recommended_allocation', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_value_eur', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_invested', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_pnl', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('holdings_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_snapshots_date'), 'portfolio_snapshots', ['date'], unique=True)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('commission', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_invested', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('broker_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transactions_asset_date', 'transactions', ['asset_id', 'date'], unique=False)
    op.create_index(op.f('ix_transactions_asset_id'), 'transactions', ['asset_id'], unique=False)
    op.create_index(op.f('ix_transactions_date'), 'transactions', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_asset_id'), table_name='transactions')
    op.drop_index('ix_transactions_asset_date', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_portfolio_snapshots_date'), table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    op.drop_table('investor_profiles')
    op.drop_table('brokers')
    op.drop_index(op.f('ix_assets_ticker'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
